from Menu import Menu
from Notebook import Notebook
from Notebook import Note

print('Notebook')
print('Attributes:')
print("Notebook: ", dir(Notebook))
print('__init__ :', dir(Notebook.__init__))
print('new_note:', dir(Notebook.new_note))
print('_find_note:', dir(Notebook._find_note))
print('modify_memo:', dir(Notebook.modify_memo))
print('modify_tags:', dir(Notebook.modify_tags))
print('search:', dir(Notebook.search))
print("Type:")
print("Notebook: ", type(Notebook))
print("__init__: ", type(Notebook.__init__))
print("modify_memo: ", type(Notebook.modify_memo))
print("isinstance:")
print("Notebook - object: ", isinstance(Notebook, object))
print('__init__ - object: ', isinstance(Notebook.__init__, object))
print('new_note - object: ', isinstance(Notebook.new_note, object))
print('_find_note - object: ', isinstance(Notebook._find_note, object))
print('modify_memo - object: ', isinstance(Notebook.modify_memo, object))
print('modify_tags - object: ', isinstance(Notebook.modify_tags, object))
print('search - object: ', isinstance(Notebook.search, object))

print('\nMenu')
print('Attributes:')
print("Menu: ", dir(Menu))
print("display.menu:", dir(Menu.display_menu))
print("run:", dir(Menu.run))
print("show_notes:", dir(Menu.show_notes))
print("search_notes:", dir(Menu.search_notes))
print("add_note:", dir(Menu.add_note))
print("modify_note:", dir(Menu.modify_note))
print("quit:", dir(Menu.quit))
print("Type:")
print("Menu: ", type(Menu))
print("display.menu:", type(Menu.display_menu))
print("run:", type(Menu.run))
print("show_notes:", type(Menu.show_notes))
print("search_notes:", type(Menu.search_notes))
print("add_note:", type(Menu.add_note))
print("modify_note:", type(Menu.modify_note))
print("quit:", type(Menu.quit))
print("isinstance:")
print("Menu - object: ", isinstance(Menu, object))

text = Note("Hello world")
print('\nNote')
print('Attributes:')
print("Note: ", dir(Note))
print("id: ", dir(text.id))
print("memo: ", dir(text.memo))
print("match: ", dir(text.match))
print("tags: ", dir(text.tags))
print("Type:")
print("Note: ", type(Note))
print("id: ", type(text.id))
print("memo: ", type(text.memo))
print("match: ", type(text.match))
print("Match:")
print(text.match("you"))
print(text.match("world"))
print("Dictionary:")
print(text.__dict__)
print("isinstance:")
print("Note - object: ", isinstance(Note, object))
print("id - int: ", isinstance(text.id, int))
print("memo - str: ", isinstance(text.memo, str))

